name: CI

on:
  push:
  pull_request:

jobs:
  run-tests:
    name: Run Tests
    
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.8.2
      
    - name: Run Tests
      run: dotnet test
